version: '3.3'
services:
  tax_calculator_golang_service:
    build:
      context: ./config
      dockerfile: golang-service
    container_name: tax_calculator_golang_service
    ports:
    - '3000:3000'
    volumes:
    - './src:/my_app:rw'
    - './storage/go/src:/go/src'
    - './config:/config:rw'
    networks:
      tax_calculator_network:
        ipv4_address: 172.16.235.10
    working_dir: "/my_app"
    command: ["sh", "-c", "go get -v -d && refresh init && refresh run"]
  tax_calculator_mysql_service:
    build:
      context: ./config
      dockerfile: mysql-service
    container_name: tax_calculator_mysql_service
    environment:
      MYSQL_DATABASE: "tax_calculator_database"
      MYSQL_USER: "tax_calculator_username"
      MYSQL_PASSWORD: "tax_calculator_password"
      MYSQL_ROOT_PASSWORD: "tax_calculator_password"
    ports:
    - '3309:3306'
    volumes:
    - './storage/mysql:/var/lib/mysql'
    - './storage/go/src:/go/src'
    - './src:/my_app:rw'
    - './config:/config:rw'
    networks:
      tax_calculator_network:
        ipv4_address: 172.16.235.11
networks:
  tax_calculator_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
      - subnet: 172.16.235.0/24